pipeline:
  name: API PR Pipeline
  identifier: API_PR_Pipeline
  tags: {}
  template:
    templateRef: API_PR_Pipeline
    versionLabel: "1"
    templateInputs:
      properties:
        ci:
          codebase:
            connectorRef: <+input>
            repoName: <+input>
            build: <+input>
      stages:
        - stage:
            identifier: Build
            template:
              templateInputs:
                type: CI
                spec:
                  infrastructure:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+input>
                      namespace: <+input>
                  execution:
                    steps:
                      - step:
                          identifier: Validate
                          type: Run
                          spec:
                            connectorRef: <+input>
                            image: <+input>
                      - step:
                          identifier: Code_Generation
                          type: Run
                          spec:
                            connectorRef: <+input>
                            image: <+input>
                      - step:
                          identifier: Create_Artifact
                          type: Run
                          spec:
                            connectorRef: <+input>
                            image: <+input>
                      - step:
                          identifier: Upload_Artifact
                          type: ArtifactoryUpload
                          spec:
                            connectorRef: <+input>
                variables:
                  - name: artifactId
                    type: String
                    value: <+input>
                  - name: groupId
                    type: String
                    value: <+input>
                  - name: mavenRepository
                    type: String
                    value: <+input>
  projectIdentifier: Test_Bed
  orgIdentifier: default
